/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';
import { Queue } from 'workbox-background-sync';

declare const self: ServiceWorkerGlobalScope;

// Take control of all clients immediately
clientsClaim();

// Clean up old precaches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
const manifest = self.__WB_MANIFEST;
precacheAndRoute(manifest);

// Cache the app shell (HTML navigation requests)
if (manifest.length > 0) {
  try {
    const handler = createHandlerBoundToURL('/index.html');
    const navigationRoute = new NavigationRoute(handler, {
      denylist: [/^\/_/, /\/[^/?]+\.[^/]+$/],
    });
    registerRoute(navigationRoute);
  } catch (e) {
    console.warn('Navigation route not registered:', e);
  }
}

// Cache Google Fonts stylesheets
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Cache Google Fonts webfonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 30,
      }),
    ],
  })
);

// Cache images with a Cache First strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// API requests - Network First with fallback to cache
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// ============================================
// BACKGROUND SYNC QUEUE
// ============================================

// Create a queue for offline sync operations
const syncQueue = new Queue('offline-sync-queue', {
  onSync: async ({ queue }) => {
    let entry;
    while ((entry = await queue.shiftRequest())) {
      try {
        const response = await fetch(entry.request);
        if (!response.ok) {
          throw new Error(`HTTP ${response.status}`);
        }
        console.log('Background sync successful:', entry.request.url);
      } catch (error) {
        console.error('Background sync failed:', error);
        // Re-queue the request for retry
        await queue.unshiftRequest(entry);
        throw error;
      }
    }
  },
});

// Intercept fetch requests and queue them if offline
self.addEventListener('fetch', (event) => {
  const { request } = event;
  
  // Only queue POST, PUT, DELETE requests (mutations)
  if (['POST', 'PUT', 'DELETE'].includes(request.method)) {
    // Check if we're offline
    if (!navigator.onLine) {
      const promiseChain = syncQueue.pushRequest({ request });
      event.waitUntil(promiseChain);
      return;
    }
  }
});

// ============================================
// PERIODIC BACKGROUND SYNC
// ============================================

self.addEventListener('periodicsync', (event: any) => {
  if (event.tag === 'check-monthiversary') {
    event.waitUntil(checkAndNotifyMonthiversary());
  }
});

// ============================================
// NOTIFICATION HANDLERS
// ============================================

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  const notificationData = event.notification.data || {};
  const urlToOpen = notificationData.url || '/';
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList: readonly WindowClient[]) => {
        // If a window is already open, focus it
        for (const client of clientList) {
          if (client.url === new URL(urlToOpen, self.location.origin).href && 'focus' in client) {
            return client.focus();
          }
        }
        // Otherwise open a new window
        if (self.clients.openWindow) {
          return self.clients.openWindow(urlToOpen);
        }
      })
  );
});

self.addEventListener('notificationclose', (event) => {
  // Handle notification close if needed
  console.log('Notification closed:', event.notification.tag);
});

// ============================================
// MESSAGE HANDLERS
// ============================================

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  
  if (event.data && event.data.type === 'QUEUE_SYNC') {
    // Queue a sync operation manually
    const { url, method, body } = event.data.payload;
    const request = new Request(url, {
      method,
      body: body ? JSON.stringify(body) : undefined,
      headers: { 'Content-Type': 'application/json' },
    });
    syncQueue.pushRequest({ request });
  }
  
  if (event.data && event.data.type === 'CHECK_MONTHIVERSARY') {
    event.waitUntil(checkAndNotifyMonthiversary());
  }
});

// ============================================
// MONTHIVERSARY CHECK
// ============================================

async function checkAndNotifyMonthiversary(): Promise<void> {
  try {
    // Open IndexedDB to get settings
    const db = await openDatabase();
    const settings = await getSettings(db);
    
    if (!settings || !settings.notificationsEnabled) {
      return;
    }
    
    const startDate = new Date(settings.relationshipStartDate);
    const today = new Date();
    
    // Check if today is a monthiversary
    const isMonthiversary = checkIfMonthiversary(startDate, today);
    
    if (isMonthiversary) {
      const months = calculateMonths(startDate, today);
      
      await self.registration.showNotification('Happy Monthiversary! 💕', {
        body: `${months} months of love together! ${settings.messageTemplate || ''}`,
        icon: '/icons/icon-192.png',
        badge: '/icons/icon-192-maskable.png',
        tag: 'monthiversary',
        requireInteraction: true,
        data: {
          url: '/',
          type: 'monthiversary',
        },
      });
    }
  } catch (error) {
    console.error('Error checking monthiversary:', error);
  }
}

function checkIfMonthiversary(startDate: Date, today: Date): boolean {
  const startDay = startDate.getDate();
  const todayDay = today.getDate();
  const todayMonth = today.getMonth();
  const todayYear = today.getFullYear();
  
  // Same day of month
  if (startDay === todayDay) {
    return true;
  }
  
  // Handle end-of-month edge case
  const lastDayOfMonth = new Date(todayYear, todayMonth + 1, 0).getDate();
  if (startDay > lastDayOfMonth && todayDay === lastDayOfMonth) {
    return true;
  }
  
  return false;
}

function calculateMonths(startDate: Date, today: Date): number {
  const months = (today.getFullYear() - startDate.getFullYear()) * 12;
  return months + today.getMonth() - startDate.getMonth();
}

// ============================================
// INDEXEDDB HELPERS
// ============================================

const DB_NAME = 'lovellevel-db';
const DB_VERSION = 1;

async function openDatabase(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open(DB_NAME, DB_VERSION);
    
    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);
    
    request.onupgradeneeded = (event) => {
      const db = (event.target as IDBOpenDBRequest).result;
      if (!db.objectStoreNames.contains('settings')) {
        db.createObjectStore('settings', { keyPath: 'id' });
      }
    };
  });
}

async function getSettings(db: IDBDatabase): Promise<any> {
  return new Promise((resolve, reject) => {
    const transaction = db.transaction('settings', 'readonly');
    const store = transaction.objectStore('settings');
    const request = store.get('settings');
    
    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);
  });
}
