/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

// Take control of all clients immediately
clientsClaim();

// Clean up old precaches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache the app shell (HTML navigation requests)
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler, {
  denylist: [/^\/_/, /\/[^/?]+\.[^/]+$/],
});
registerRoute(navigationRoute);

// Cache Google Fonts
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 30,
      }),
    ],
  })
);

// Cache images with a Cache First strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Listen for messages from the client
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});

// Notification scheduling (check for monthiversaries)
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    // @ts-ignore
    clients.openWindow('/')
  );
});

// Background sync for offline actions (future enhancement)
self.addEventListener('sync', (event: any) => {
  if (event.tag === 'sync-data') {
    event.waitUntil(
      // Implement data sync logic here
      Promise.resolve()
    );
  }
});

// Periodic background sync for monthiversary checks
self.addEventListener('periodicsync', (event: any) => {
  if (event.tag === 'check-monthiversary') {
    event.waitUntil(
      // Check if today is a monthiversary and show notification
      checkAndNotifyMonthiversary()
    );
  }
});

async function checkAndNotifyMonthiversary() {
  try {
    // This would read from IndexedDB and check dates
    // For now, this is a placeholder
    // In a real implementation, we'd open IndexedDB, get the relationship start date,
    // calculate if today is a monthiversary, and show a notification
    const registration = self.registration;
    
    // Placeholder logic - replace with actual date checking
    const isMonthiversary = false; // await checkMonthiversaryFromDB();
    
    if (isMonthiversary) {
      await registration.showNotification('Happy Monthiversary! 💕', {
        body: 'Another month of love together!',
        icon: '/icons/icon-192.png',
        badge: '/icons/icon-192-maskable.png',
        tag: 'monthiversary',
        requireInteraction: true,
      });
    }
  } catch (error) {
    console.error('Error checking monthiversary:', error);
  }
}
